version: '3.9'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp_dock_comp:1.0
    ports:
      - "80:5000"
    restart: always
    networks:
      - webnet
networks:
  webnet:

